#!/usr/bin/env bash
# Write the deployed fleet's A2A base URLs and agent identity principals to
# infra/fleet_endpoints.env.
#
# Agent Runtime exposes each container's HTTP routes under an /api passthrough, so a specialist's
# A2A base is:
#   https://{region}-aiplatform.googleapis.com/reasoningEngines/v1/{resource}/api
#
# When --agent-identity is enabled, each engine also has an effective_identity: the platform-managed
# principal that google.auth.default() returns inside the engine. These are exported as
# CASERELAY_IDENTITY_* so the gateway and grant system can match callers to grants.
#
# Source the generated file before deploying the orchestrator so it can resolve its specialists.
set -uo pipefail

PROJECT="${CASERELAY_PROJECT:-caserelay}"
REGION="${CASERELAY_REGION:-us-central1}"
OUT="$(dirname "$0")/fleet_endpoints.env"
TOKEN="$(gcloud auth print-access-token)"

curl -s -H "Authorization: Bearer ${TOKEN}" \
  "https://${REGION}-aiplatform.googleapis.com/v1beta1/projects/${PROJECT}/locations/${REGION}/reasoningEngines" |
  REGION="$REGION" python3 -c '
import json, os, sys

region = os.environ["REGION"]
var_by_agent = {
    "education_liaison": "CASERELAY_URL_EDUCATION",
    "health_coordination": "CASERELAY_URL_HEALTH",
    "legal_aid": "CASERELAY_URL_LEGAL",
    "shelter_status": "CASERELAY_URL_SHELTER",
    "family_services": "CASERELAY_URL_FAMILY",
    "safeguarding_verifier": "CASERELAY_URL_VERIFIER",
    "intake_authority": "CASERELAY_URL_INTAKE",
    "continuity_orchestrator": "CASERELAY_URL_ORCHESTRATOR",
}
identity_by_agent = {
    "education_liaison": "CASERELAY_IDENTITY_EDUCATION",
    "health_coordination": "CASERELAY_IDENTITY_HEALTH",
    "legal_aid": "CASERELAY_IDENTITY_LEGAL",
    "shelter_status": "CASERELAY_IDENTITY_SHELTER",
    "family_services": "CASERELAY_IDENTITY_FAMILY",
    "safeguarding_verifier": "CASERELAY_IDENTITY_VERIFIER",
    "intake_authority": "CASERELAY_IDENTITY_INTAKE",
    "continuity_orchestrator": "CASERELAY_IDENTITY_ORCHESTRATOR",
}

display_to_agent = {
    "caserelay-education": "education_liaison",
    "caserelay-health": "health_coordination",
    "caserelay-legal": "legal_aid",
    "caserelay-shelter": "shelter_status",
    "caserelay-family": "family_services",
    "caserelay-verifier": "safeguarding_verifier",
    "caserelay-intake": "intake_authority",
    "caserelay-orchestrator": "continuity_orchestrator",
}

lines = ["# generated by infra/collect_endpoints.sh"]
for e in json.load(sys.stdin).get("reasoningEngines", []):
    spec = e.get("spec", {}) or {}
    deploy = spec.get("deploymentSpec", {}) or {}
    env = {v.get("name"): v.get("value") for v in deploy.get("env", []) or []}
    agent = env.get("CASERELAY_AGENT")
    if agent not in var_by_agent:
        agent = display_to_agent.get(e.get("displayName", ""))
    if agent not in var_by_agent:
        continue
    resource = e["name"]
    base = "https://%s-aiplatform.googleapis.com/reasoningEngines/v1/%s/api" % (region, resource)
    lines.append("export %s=%s" % (var_by_agent[agent], base))
    lines.append("export %s_RESOURCE=%s" % (var_by_agent[agent], resource))
    eff_id = spec.get("effectiveIdentity") or spec.get("effective_identity", "")
    if eff_id and agent in identity_by_agent:
        lines.append("export %s=%s" % (identity_by_agent[agent], eff_id))
print("\n".join(lines))
' >"$OUT"

echo "wrote $OUT"
cat "$OUT"
